15:15:33,700 (main) WARN  [DataNucleus.Datastore.Persist] - Persistencia del objeto "ld.Usuario@1f97cf0d" con SQL "INSERT INTO `USUARIO` (`EMAIL`,`EMPRESA`,`LOCALIZACION`,`NOMUSUARIO`,`ORG_IDORG_OID`,`IDUSUARIO`) VALUES (?,?,?,?,?,?)" ha tirado un error : Duplicate entry '1' for key 'PRIMARY'
15:49:49,720 (main) WARN  [DataNucleus.Datastore.Persist] - Persistencia del objeto "ld.Usuario@366647c2" con SQL "INSERT INTO `USUARIO` (`EMAIL`,`EMPRESA`,`LOCALIZACION`,`NOMUSUARIO`,`ORG_IDORG_OID`,`IDUSUARIO`) VALUES (?,?,?,?,?,?)" ha tirado un error : Duplicate entry '3' for key 'PRIMARY'
20:38:43,259 (main) WARN  [DataNucleus.Datastore.Persist] - Persistencia del objeto "ld.Repositorio@2679311f" con SQL "INSERT INTO `REPOSITORIO` (`DESCRIPCION`,`FECHACREACION`,`NOMREPO`,`ORGANIZACION`,`ULTIMAACTUALIZACION`,`USUARIO`,`IDREPO`) VALUES (?,?,?,?,?,?,?)" ha tirado un error : Duplicate entry '368555994' for key 'PRIMARY'
20:41:16,798 (main) WARN  [DataNucleus.Datastore.Persist] - Persistencia del objeto "ld.Repositorio@290aeb20" con SQL "INSERT INTO `REPOSITORIO` (`DESCRIPCION`,`FECHACREACION`,`NOMREPO`,`ORGANIZACION`,`ULTIMAACTUALIZACION`,`USUARIO`,`IDREPO`) VALUES (?,?,?,?,?,?,?)" ha tirado un error : Duplicate entry '368555994' for key 'PRIMARY'
20:45:28,260 (main) WARN  [DataNucleus.Datastore.Persist] - Persistencia del objeto "ld.Usuario@38548b19" con SQL "INSERT INTO `USUARIO` (`EMAIL`,`EMPRESA`,`LOCALIZACION`,`NOMUSUARIO`,`IDUSUARIO`) VALUES (?,?,?,?,?)" ha tirado un error : Duplicate entry '55877206' for key 'PRIMARY'
20:45:32,939 (main) WARN  [DataNucleus.Datastore.Persist] - Persistencia del objeto "ld.Repositorio@6f7e336b" con SQL "INSERT INTO `REPOSITORIO` (`DESCRIPCION`,`FECHACREACION`,`NOMREPO`,`ORGANIZACION`,`ULTIMAACTUALIZACION`,`USUARIO`,`IDREPO`) VALUES (?,?,?,?,?,?,?)" ha tirado un error : Duplicate entry '368555994' for key 'PRIMARY'
20:45:37,006 (main) WARN  [DataNucleus.Datastore.Persist] - Persistencia del objeto "ld.Usuario@38548b19" con SQL "INSERT INTO `USUARIO` (`EMAIL`,`EMPRESA`,`LOCALIZACION`,`NOMUSUARIO`,`IDUSUARIO`) VALUES (?,?,?,?,?)" ha tirado un error : Duplicate entry '55877206' for key 'PRIMARY'
20:50:31,771 (main) WARN  [DataNucleus.Datastore.Persist] - Persistencia del objeto "ld.Usuario@71391b3f" con SQL "INSERT INTO `USUARIO` (`EMAIL`,`EMPRESA`,`LOCALIZACION`,`NOMUSUARIO`,`IDUSUARIO`) VALUES (?,?,?,?,?)" ha tirado un error : Duplicate entry '55877206' for key 'PRIMARY'
20:50:35,928 (main) WARN  [DataNucleus.Datastore.Persist] - Persistencia del objeto "ld.Repositorio@24e08d59" con SQL "INSERT INTO `REPOSITORIO` (`DESCRIPCION`,`FECHACREACION`,`NOMREPO`,`ORGANIZACION`,`ULTIMAACTUALIZACION`,`USUARIO`,`IDREPO`) VALUES (?,?,?,?,?,?,?)" ha tirado un error : Duplicate entry '368555994' for key 'PRIMARY'
20:50:39,906 (main) WARN  [DataNucleus.Datastore.Persist] - Persistencia del objeto "ld.Usuario@71391b3f" con SQL "INSERT INTO `USUARIO` (`EMAIL`,`EMPRESA`,`LOCALIZACION`,`NOMUSUARIO`,`IDUSUARIO`) VALUES (?,?,?,?,?)" ha tirado un error : Duplicate entry '55877206' for key 'PRIMARY'
20:57:01,440 (main) WARN  [DataNucleus.Datastore.Persist] - Persistencia del objeto "ld.Usuario@198ef2ce" con SQL "INSERT INTO `USUARIO` (`EMAIL`,`EMPRESA`,`LOCALIZACION`,`NOMUSUARIO`,`IDUSUARIO`) VALUES (?,?,?,?,?)" ha tirado un error : Duplicate entry '55877206' for key 'PRIMARY'
20:57:05,774 (main) WARN  [DataNucleus.Datastore.Persist] - Persistencia del objeto "ld.Repositorio@1abc9f14" con SQL "INSERT INTO `REPOSITORIO` (`DESCRIPCION`,`FECHACREACION`,`NOMREPO`,`ORGANIZACION`,`ULTIMAACTUALIZACION`,`USUARIO`,`IDREPO`) VALUES (?,?,?,?,?,?,?)" ha tirado un error : Duplicate entry '368555994' for key 'PRIMARY'
20:57:10,237 (main) WARN  [DataNucleus.Datastore.Persist] - Persistencia del objeto "ld.Usuario@198ef2ce" con SQL "INSERT INTO `USUARIO` (`EMAIL`,`EMPRESA`,`LOCALIZACION`,`NOMUSUARIO`,`IDUSUARIO`) VALUES (?,?,?,?,?)" ha tirado un error : Duplicate entry '55877206' for key 'PRIMARY'
11:43:36,464 (main) WARN  [DataNucleus.Datastore.Persist] - Persistencia del objeto "ld.Usuario@7068f7ca" con SQL "INSERT INTO `USUARIO` (`EMAIL`,`EMPRESA`,`LOCALIZACION`,`NOMUSUARIO`,`IDUSUARIO`) VALUES (?,?,?,?,?)" ha tirado un error : Duplicate entry '63655046' for key 'PRIMARY'
11:43:41,248 (main) WARN  [DataNucleus.Datastore.Persist] - Persistencia del objeto "ld.Repositorio@6f7e336b" con SQL "INSERT INTO `REPOSITORIO` (`DESCRIPCION`,`FECHACREACION`,`NOMREPO`,`ORGANIZACION`,`ULTIMAACTUALIZACION`,`USUARIO`,`IDREPO`) VALUES (?,?,?,?,?,?,?)" ha tirado un error : Duplicate entry '368555994' for key 'PRIMARY'
11:46:12,546 (main) WARN  [DataNucleus.Datastore.Persist] - Persistencia del objeto "ld.Repositorio@290aeb20" con SQL "INSERT INTO `REPOSITORIO` (`DESCRIPCION`,`FECHACREACION`,`NOMREPO`,`ORGANIZACION`,`ULTIMAACTUALIZACION`,`USUARIO`,`IDREPO`) VALUES (?,?,?,?,?,?,?)" ha tirado un error : Duplicate entry '368555994' for key 'PRIMARY'
11:46:18,001 (main) WARN  [DataNucleus.Datastore.Persist] - Persistencia del objeto "ld.Usuario@730e5763" con SQL "INSERT INTO `USUARIO` (`EMAIL`,`EMPRESA`,`LOCALIZACION`,`NOMUSUARIO`,`IDUSUARIO`) VALUES (?,?,?,?,?)" ha tirado un error : Duplicate entry '63655046' for key 'PRIMARY'
11:53:35,169 (main) WARN  [DataNucleus.Datastore.Persist] - Persistencia del objeto "ld.Repositorio@3c904f1e" con SQL "INSERT INTO `REPOSITORIO` (`DESCRIPCION`,`FECHACREACION`,`NOMREPO`,`ORGANIZACION`,`ULTIMAACTUALIZACION`,`USUARIO`,`IDREPO`) VALUES (?,?,?,?,?,?,?)" ha tirado un error : Duplicate entry '368555994' for key 'PRIMARY'
11:53:39,829 (main) WARN  [DataNucleus.Datastore.Persist] - Persistencia del objeto "ld.Usuario@45d64d27" con SQL "INSERT INTO `USUARIO` (`EMAIL`,`EMPRESA`,`LOCALIZACION`,`NOMUSUARIO`,`IDUSUARIO`) VALUES (?,?,?,?,?)" ha tirado un error : Duplicate entry '63655046' for key 'PRIMARY'
12:02:14,903 (main) WARN  [DataNucleus.Datastore.Persist] - Persistencia del objeto "ld.Usuario@a7f0ab6" con SQL "INSERT INTO `USUARIO` (`EMAIL`,`EMPRESA`,`LOCALIZACION`,`NOMUSUARIO`,`IDUSUARIO`) VALUES (?,?,?,?,?)" ha tirado un error : Duplicate entry '63655046' for key 'PRIMARY'
12:02:19,863 (main) WARN  [DataNucleus.Datastore.Persist] - Persistencia del objeto "ld.Repositorio@38704ff0" con SQL "INSERT INTO `REPOSITORIO` (`DESCRIPCION`,`FECHACREACION`,`NOMREPO`,`ORGANIZACION`,`ULTIMAACTUALIZACION`,`USUARIO`,`IDREPO`) VALUES (?,?,?,?,?,?,?)" ha tirado un error : Duplicate entry '368555994' for key 'PRIMARY'
12:04:01,461 (main) WARN  [DataNucleus.Query] - Query for candidates of ld.Commit and subclasses resulted in no possible candidates : La clase "ld.Commit" no tiene una tabla en la base de datos, pero esta operacion la necesita. Por favor compruebe el MetaData
12:06:04,792 (main) WARN  [DataNucleus.Datastore.Persist] - Persistencia del objeto "ld.Commit@13d186db" con SQL "INSERT INTO `COMMIT` (`NOMCOMMIT`,`REPOSITORIO`,`USUARIO`,`IDCOMMIT`,`LISTACOMMITS_INTEGER_IDX`) VALUES (?,?,?,?,?)" ha tirado un error : Incorrect integer value: 'MDY6Q29tbWl0MzY4NTU1OTk0OmJjZDZjNzhkNDI0Zjk1MzlkYzA4ZTdjZWEwYWIzYzM2MWViYTg1NTM=' for column 'IDCOMMIT' at row 1
23:00:46,917 (main) ERROR [DataNucleus.Datastore.Schema] - La inicializaci√≥n del base de datos ha fallado.
User lS8RYCUze2 already has more than 'max_user_connections' active connections
org.datanucleus.exceptions.NucleusDataStoreException: User lS8RYCUze2 already has more than 'max_user_connections' active connections
	at org.datanucleus.store.rdbms.ConnectionFactoryImpl$ManagedConnectionImpl.getConnection(ConnectionFactoryImpl.java:513)
	at org.datanucleus.store.rdbms.RDBMSStoreManager.<init>(RDBMSStoreManager.java:288)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.datanucleus.plugin.NonManagedPluginRegistry.createExecutableExtension(NonManagedPluginRegistry.java:651)
	at org.datanucleus.plugin.PluginManager.createExecutableExtension(PluginManager.java:295)
	at org.datanucleus.NucleusContextHelper.createStoreManagerForProperties(NucleusContextHelper.java:140)
	at org.datanucleus.PersistenceNucleusContextImpl.initialise(PersistenceNucleusContextImpl.java:447)
	at org.datanucleus.api.jdo.JDOPersistenceManagerFactory.freezeConfiguration(JDOPersistenceManagerFactory.java:859)
	at org.datanucleus.api.jdo.JDOPersistenceManagerFactory.createPersistenceManagerFactory(JDOPersistenceManagerFactory.java:346)
	at org.datanucleus.api.jdo.JDOPersistenceManagerFactory.getPersistenceManagerFactory(JDOPersistenceManagerFactory.java:225)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at javax.jdo.JDOHelper$16.run(JDOHelper.java:1975)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.jdo.JDOHelper.invoke(JDOHelper.java:1970)
	at javax.jdo.JDOHelper.invokeGetPersistenceManagerFactoryOnImplementation(JDOHelper.java:1177)
	at javax.jdo.JDOHelper.getPersistenceManagerFactory(JDOHelper.java:814)
	at javax.jdo.JDOHelper.getPersistenceManagerFactory(JDOHelper.java:1093)
	at javax.jdo.JDOHelper.getPersistenceManagerFactory(JDOHelper.java:924)
	at dao.CommitDAO.limpiarBD(CommitDAO.java:54)
	at dao.CommitDAO.extraerCommits(CommitDAO.java:18)
	at appServices.CommitService.<init>(CommitService.java:17)
	at facade.Facade.main(Facade.java:47)
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: User lS8RYCUze2 already has more than 'max_user_connections' active connections
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:944)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3973)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:873)
	at com.mysql.jdbc.MysqlIO.proceedHandshakeWithPluggableAuthentication(MysqlIO.java:1710)
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1226)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2188)
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2219)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2014)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:776)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:386)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:330)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:208)
	at org.datanucleus.store.rdbms.datasource.dbcp2.DriverManagerConnectionFactory.createConnection(DriverManagerConnectionFactory.java:123)
	at org.datanucleus.store.rdbms.datasource.dbcp2.PoolableConnectionFactory.makeObject(PoolableConnectionFactory.java:353)
	at org.datanucleus.store.rdbms.datasource.dbcp2.pool2.impl.GenericObjectPool.create(GenericObjectPool.java:899)
	at org.datanucleus.store.rdbms.datasource.dbcp2.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:429)
	at org.datanucleus.store.rdbms.datasource.dbcp2.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:354)
	at org.datanucleus.store.rdbms.datasource.dbcp2.PoolingDataSource.getConnection(PoolingDataSource.java:132)
	at org.datanucleus.store.rdbms.ConnectionFactoryImpl$ManagedConnectionImpl.getConnection(ConnectionFactoryImpl.java:496)
	... 27 more
Nested Throwables StackTrace:
com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: User lS8RYCUze2 already has more than 'max_user_connections' active connections
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:944)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3973)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:873)
	at com.mysql.jdbc.MysqlIO.proceedHandshakeWithPluggableAuthentication(MysqlIO.java:1710)
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1226)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2188)
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2219)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2014)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:776)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:386)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:330)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:208)
	at org.datanucleus.store.rdbms.datasource.dbcp2.DriverManagerConnectionFactory.createConnection(DriverManagerConnectionFactory.java:123)
	at org.datanucleus.store.rdbms.datasource.dbcp2.PoolableConnectionFactory.makeObject(PoolableConnectionFactory.java:353)
	at org.datanucleus.store.rdbms.datasource.dbcp2.pool2.impl.GenericObjectPool.create(GenericObjectPool.java:899)
	at org.datanucleus.store.rdbms.datasource.dbcp2.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:429)
	at org.datanucleus.store.rdbms.datasource.dbcp2.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:354)
	at org.datanucleus.store.rdbms.datasource.dbcp2.PoolingDataSource.getConnection(PoolingDataSource.java:132)
	at org.datanucleus.store.rdbms.ConnectionFactoryImpl$ManagedConnectionImpl.getConnection(ConnectionFactoryImpl.java:496)
	at org.datanucleus.store.rdbms.RDBMSStoreManager.<init>(RDBMSStoreManager.java:288)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.datanucleus.plugin.NonManagedPluginRegistry.createExecutableExtension(NonManagedPluginRegistry.java:651)
	at org.datanucleus.plugin.PluginManager.createExecutableExtension(PluginManager.java:295)
	at org.datanucleus.NucleusContextHelper.createStoreManagerForProperties(NucleusContextHelper.java:140)
	at org.datanucleus.PersistenceNucleusContextImpl.initialise(PersistenceNucleusContextImpl.java:447)
	at org.datanucleus.api.jdo.JDOPersistenceManagerFactory.freezeConfiguration(JDOPersistenceManagerFactory.java:859)
	at org.datanucleus.api.jdo.JDOPersistenceManagerFactory.createPersistenceManagerFactory(JDOPersistenceManagerFactory.java:346)
	at org.datanucleus.api.jdo.JDOPersistenceManagerFactory.getPersistenceManagerFactory(JDOPersistenceManagerFactory.java:225)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at javax.jdo.JDOHelper$16.run(JDOHelper.java:1975)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.jdo.JDOHelper.invoke(JDOHelper.java:1970)
	at javax.jdo.JDOHelper.invokeGetPersistenceManagerFactoryOnImplementation(JDOHelper.java:1177)
	at javax.jdo.JDOHelper.getPersistenceManagerFactory(JDOHelper.java:814)
	at javax.jdo.JDOHelper.getPersistenceManagerFactory(JDOHelper.java:1093)
	at javax.jdo.JDOHelper.getPersistenceManagerFactory(JDOHelper.java:924)
	at dao.CommitDAO.limpiarBD(CommitDAO.java:54)
	at dao.CommitDAO.extraerCommits(CommitDAO.java:18)
	at appServices.CommitService.<init>(CommitService.java:17)
	at facade.Facade.main(Facade.java:47)
23:00:46,932 (main) ERROR [DataNucleus.Datastore] - Exception thrown creating StoreManager : User lS8RYCUze2 already has more than 'max_user_connections' active connections
